CREATE SCHEMA BANK;

CREATE TABLE BANK.CUSTOMER
(
    ID   INTEGER     NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50) NOT NULL,
    IBAN VARCHAR(34) NOT NULL,
    SEX  CHARACTER   NOT NULL,

    CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID),
    CONSTRAINT IBAN_UNIQUE UNIQUE (IBAN),
    CONSTRAINT IBAN_CHECK CHECK (IBAN LIKE 'DE%' AND LENGTH(IBAN) >= 12 AND IBAN = UPPER(IBAN)),
    CONSTRAINT SEX_CHECK CHECK (SEX IN ('m', 'f', 'd') AND SEX = LOWER(SEX))
);

CREATE TABLE BANK.TRANSFER
(
    ID              BIGINT         NOT NULL GENERATED ALWAYS AS IDENTITY,
    TRANSFER_NUMBER BIGINT         NOT NULL,
    SENDER          INTEGER        NOT NULL,
    RECEIVER        INTEGER        NOT NULL,
    AMOUNT          DECIMAL(10, 2) NOT NULL,
    TIMESTAMP       TIMESTAMP      NOT NULL,
    SUBJECT         VARCHAR(140)   NOT NULL,
    INTERNAL_NOTE   CLOB,

    CONSTRAINT TRANSFER_PK PRIMARY KEY (ID),
    CONSTRAINT TRANSFER_NUMBER_UNIQUE UNIQUE (TRANSFER_NUMBER),
    CONSTRAINT SENDER_FK FOREIGN KEY (SENDER) REFERENCES CUSTOMER (ID),
    CONSTRAINT RECEIVER_FK FOREIGN KEY (RECEIVER) REFERENCES CUSTOMER (ID),
    CONSTRAINT AMOUNT_CHECK CHECK (AMOUNT > 0)
);
